import { Nunito } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

// const ubuntu = Nunito({
//   variable: "--font-ubuntu",
//   subsets: ["latin"],
//   weight: ["400", "500", "700"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Toaster />
        {children}
      </body>
    </html>
  );
}
